### ISSUE TITLE
Availability of documentation

### ISSUE THREAD

**Issue by Phonetiker** [arpit7123/K-Parser-JAR#1]
Hi Arpit,
Is there any possibility that the documentation (current or archival) could be made available for this project? The link for that doesn't seem to be active any more: http://bioai8core.fulton.asu.edu/kparserdoc/
Many thanks!

**Comment by arpit7123** [comment]
The source code of K-Parser is also available in https://github.com/arpit7123/Kparser. It can be used to generate javadocs in an IDE software (it is originally an eclipse project) which will have details of each class in the project.
